#%RAML 0.8
title: CreditUnionCC
version: 1.0
baseUri: /mobile/custom/CreditUnionCC
protocols: [HTTPS]
/components:
  get:
    displayName: Get Metadata
    description: |
      Get all component metadata
      
    protocols: [HTTPS]
    responses:
      200:
        description: |
          All component metadata
          
        body:
          application/json:
  /{componentName}:
    uriParameters:
      componentName:
        displayName: componentName
        description: |
          Component name
          
        type: string
        required: true
    post:
      displayName: Invoke Component
      description: |
        Invoke component by name
        
      body:
        application/json: